version: "3.9"

services:
    web_app:
        image: webdevops/php-nginx-dev:8.2
        working_dir: /app/
        ports:
            - 8080:80
        environment:
            WEB_DOCUMENT_ROOT: /app/public
            WEB_DOCUMENT_INDEX: index.php
            XDEBUG_START_WITH_REQUEST: 1
            XDEBUG_MODE: coverage
            XDEBUG_CLIENT_HOST: host.docker.internal
            PHP_IDE_CONFIG: serverName=localhost
        volumes:
            - .:/app:cached
    data_base:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: orders
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./docker/mysql:/var/lib/mysql

